PycharmProjects/OZBargainVote/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired


class SLForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()], id='username-input')
    password = PasswordField('Password', validators=[DataRequired()], id='password-input')
    remember = BooleanField('Remember me')


class SignupForm(SLForm):
    _name = 'Signup'
    submit = SubmitField('Sign up', render_kw={'class': 'btn'}, id='signup-btn')


class LoginForm(SLForm):
    _name = 'Login'
    submit = SubmitField('Login', render_kw={'class': 'btn'}, id='login-btn')

PycharmProjects/OZBargainVote/app.py
from flask import Flask
from flask_login import LoginManager
from config import Config
from model import User
from blueprints.home import home_bp
from blueprints.auth import auth_bp
from blueprints.user import user_bp
from flask_wtf.csrf import CSRFProtect

app = Flask(__name__)


def register_blueprints(the_app):
    the_app.register_blueprint(home_bp)
    the_app.register_blueprint(auth_bp)
    the_app.register_blueprint(user_bp)


app.config.from_object(Config())
login_manager = LoginManager(app)
login_manager.login_view = 'auth.login'
CSRFProtect(app)
register_blueprints(app)


@login_manager.user_loader
def load_user(user_id):
    return User(user_id).retrieve_user_by_id()

PycharmProjects/OZBargainVote/blueprints/auth.py
from flask import render_template, Blueprint, redirect, url_for, jsonify, request
from flask_login import login_user, current_user, login_required, logout_user
from model import User

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('home.discount'))

    if request.method == 'POST':
        data = request.get_json()
        username = data['username']
        password = data['password']
        if not User().register(username, password):
            return jsonify(message='Signup failed. Please retry.'), 400
        return jsonify(message='Signup success. Please login.')
    return render_template('_signup_login.html', mode='signup')


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home.discount'))

    if request.method == 'POST':
        data = request.get_json()
        username = data['username']
        password = data['password']
        user = User().retrieve_user(username)
        if user and user.validate_password(password):
            login_user(user)
            return jsonify(message='Login success.')
        return jsonify(message='Invalid username or password.'), 400
    return render_template('_signup_login.html', mode='login')


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return jsonify(message='Logout success.')

PycharmProjects/OZBargainVote/blueprints/home.py
from flask import render_template, Blueprint, request, jsonify, redirect
from model import redis_cli

home_bp = Blueprint('home', __name__)


@home_bp.route('/')
def index():
    if request.args:
        search_content = str(request.args['search_content']).lower()
        search_item_ids = redis_cli.smembers(f'{search_content}:items')
        search_res = []
        for item_id in search_item_ids:
            product = redis_cli.hgetall(f'item:info:{item_id}')
            product['discount'] = str(round(float(product['discount']) * 100)) + '%'
            search_res.append(product)
        num_items = len(search_res)
        search_res = [search_res[i:i + 3] for i in range(0, len(search_res), 3)]
        return render_template('_search.html', search_res=search_res, num=num_items)
    return render_template('index.html')


@home_bp.route('/discount')
def discount():
    top_discount = redis_cli.zrange('discount:highest', 0, 35, desc=True, withscores=True)
    products = []
    for product_id, score in top_discount:
        product = redis_cli.hgetall(f'item:info:{product_id}')
        product['discount'] = str(round(float(product['discount']) * 100)) + '%'
        products.append(product)
    products = [products[i:i + 3] for i in range(0, len(products), 3)]
    return render_template('_discount.html', products=products)


@home_bp.route('/cheapest-in-history')
def cheapest():
    cheapest_in_history = []
    item_id_list = redis_cli.srandmember('price:lowest_history', 36)
    for item_id in item_id_list:
        product = redis_cli.hgetall(f'item:info:{item_id}')
        product['discount'] = str(round(float(product['discount']) * 100)) + '%'
        cheapest_in_history.append(product)
    cheapest_in_history = [cheapest_in_history[i:i + 3] for i in range(0, len(cheapest_in_history), 3)]
    return render_template('_cheapest_in_history.html', products=cheapest_in_history)


@home_bp.route('/like-chart')
def like_chart():
    top_products = redis_cli.zrange('like:count', 0, 9, desc=True, withscores=True)
    product_info = []
    for product_id, score in top_products:
        product = redis_cli.hgetall(f'item:info:{product_id}')
        product['like_count'] = int(score)
        product_info.append(product)
    return render_template('_like_chart.html', product_info=product_info)


@home_bp.route('/autocomplete')
def autocomplete():
    completion_content = str(request.args.get('term')).lower()
    completion_res = redis_cli.zrangebylex('brands:', '[' + completion_content, '(' + completion_content + '{')[:8]
    return jsonify(completion_res)


@home_bp.route('/brands', methods=['POST'])
def search():
    search_content = request.get_json()['search_content'].lower()
    search_item_ids = redis_cli.smembers(f'{search_content}:items')
    search_res = []
    for item_id in search_item_ids:
        product = redis_cli.hgetall(f'item:info:{item_id}')
        product['discount'] = str(round(float(product['discount']) * 100)) + '%'
        search_res.append(product)
    num_items = len(search_res)
    search_res = [search_res[i:i + 3] for i in range(0, len(search_res), 3)]
    return jsonify(html=render_template('_search.html', search_res=search_res, num=num_items))

PycharmProjects/OZBargainVote/blueprints/user.py
from flask import render_template, Blueprint
from flask_login import login_required, current_user
from model import redis_cli

user_bp = Blueprint('user', __name__)


@user_bp.route('/my-space')
def user_space():
    return render_template('_user_space.html')


@user_bp.route('/my-like')
@login_required
def my_like():
    like_product_ids = redis_cli.smembers(f'user:like:{current_user.id}')
    products = []
    for item_id in like_product_ids:
        product = redis_cli.hgetall(f'item:info:{item_id}')
        product['discount'] = str(round(float(product['discount']) * 100)) + '%'
        products.append(product)
    return render_template('_my_like.html', products=products)


@user_bp.route('/my-collection')
@login_required
def my_collection():
    star_product_ids = redis_cli.smembers(f'user:star:{current_user.id}')
    products = []
    for item_id in star_product_ids:
        product = redis_cli.hgetall(f'item:info:{item_id}')
        product['discount'] = str(round(float(product['discount']) * 100)) + '%'
        products.append(product)
    return render_template('_my_collection.html', products=products)

PycharmProjects/OZBargainVote/templates/_discount.html
{% extends 'base.html' %}

{% block content %}
<h4 align="center">今日大折扣</h4><br><br>
<table align="center">
    {% for three_products in products %}
    <tr>
        {% for product in three_products %}
        <td>
            {% if current_user and current_user.is_authenticated %}
            {% include '_like_collect.html' %}
            {% endif %}
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle">
                <div align="center" style="width:185px; height:46px">{{ product.title_chinese }}</div><br>
            </a>
            <div align="center" style="font-size:22px">${{ product.price }}</div>
            <div align="center" style="font-size:22px; color:red">{{ product.discount }} Off</div>
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

PycharmProjects/OZBargainVote/templates/_like_chart.html
{% extends 'base.html' %}

{% block content %}
<h4 align="center">点赞排行榜</h4><br><br>
<ul class="product-list">
    <li style="height:30px; font-size:20px">
        <span style="float:left; padding:0px 60px">商品</span>
        <span style="float:right; padding:0px 70px">点赞数</span>
    </li><br>
    {% for product in product_info %}
    <li>
        <span style="float:right; font-size:30px; padding:70px 100px">{{ product.like_count }}</span>
        <div style="width:165px; text-align:center">
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle"><br>
                <span style="width:35px; height:46px">{{ product.title_chinese }}</span>
            </a><br>
            <span style="font-size:19px">${{ product.price }}</span><br>
        </div>
    </li><br>
    {% endfor %}
</ul>
{% endblock %}

PycharmProjects/OZBargainVote/templates/_my_collection.html
{% extends 'base.html' %}

{% block content %}
<div align="center" style="font-size:25px">{{ current_user.username }}的领地</div><br><br>
<div align="center" style="font-size:29px">
    <a class="snu" href="#my-like">我的点赞</a>
    <a class="snu" href="#my-collection">我的收藏</a>
</div>
<ul class="product-list">
    <li style="height:30px; font-size:20px">
        <span style="float:left; padding:0px 60px">商品</span>
    </li>
    {% for product in products %}
    <li>
        <form method="get" action="{{ url_for('user.cancel_star', item_id=product.item_id) }}" style="float:right; font-size:30px; padding:70px 100px">
            <input class="snu" type="submit" name="unstar" value="取消收藏" onclick="return confirm('Are you sure?')">
        </form>
        <div style="width:165px; text-align:center">
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle"><br>
                <span style="width:35px; height:46px">{{ product.title_chinese }}</span>
            </a><br><br>
            <span style="font-size:19px">${{ product.price }}</span>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

PycharmProjects/OZBargainVote/templates/_my_like.html
{% extends 'base.html' %}

{% block content %}
<div align="center" style="font-size:25px">{{ current_user.username }}的领地</div><br><br>
<div align="center" style="font-size:29px">
    <a class="snu" href="#my-like">我的点赞</a>
    <a class="snu" href="#my-collection">我的收藏</a>
</div>
<ul class="product-list">
    <li style="height:30px; font-size:20px">
        <span style="float:left; padding:0px 60px">商品</span>
    </li>
    {% for product in products %}
    <li>
        <form method="get" action="{{ url_for('user.cancel_like', item_id=product.item_id) }}" style="float:right; font-size:30px; padding:70px 100px">
            <input class="snu" type="submit" name="unlike" value="取消赞" onclick="return confirm('Are you sure?')">
        </form>
        <div style="width:165px; text-align:center">
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle"><br>
                <span style="width:35px; height:46px">{{ product.title_chinese }}</span>
            </a><br><br>
            <span style="font-size:19px">${{ product.price }}</span>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

PycharmProjects/OZBargainVote/templates/_search.html
{% extends 'base.html' %}

{% block content %}
{% if not search_res %}
<h3>没找到您搜的品牌，请换个品牌试试</h3>
{% else %}
<h3>为您找到了{{ num }}件商品</h3>
<table align="center">
    {% for three_products in search_res %}
    <tr>
        {% for product in three_products %}
        <td>
            {% if current_user and current_user.is_authenticated %}
            {% endif %}
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle">
                <div align="center" style="width:185px; height:46px">{{ product.title_chinese }}</div>
            </a>
            <div align="center" style="font-size:22px">${{ product.price }}</div>
            <div align="center" style="font-size:22px; color:red">{{ product.discount }} Off</div>
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock %}

PycharmProjects/OZBargainVote/templates/_signup_login.html
{% extends 'base.html' %}

{% block content %}
    <header class="center">
        <h4 class="red-text">{{ mode }}</h4><br>
    </header>
    <div class="login-form">
        <input class="validate login-input" id="username-input" name="username" type="text" placeholder="Username"
               autofocus required>
        <input class="validate login-input" id="password-input" name="password" type="password" placeholder="Password"
               required>
        <span class="right">
            <a class="btn red" id="{{ mode }}-btn">Submit</a>
        </span>
    </div>
{% endblock %}

PycharmProjects/OZBargainVote/templates/base.html
<nav class="blue lighten-2" role="navigation">
    <div class="nav-wrapper container">
        <ul class="left hide-on-med-and-down">
            <li><a href="#intro" style="font-size: 2.1rem">OZBuy</a></li>
            <li><a href="#discount" class="waves-effect waves-light">今日大折扣</a></li>
            <li><a href="#cheapest-in-history" class="waves-effect waves-light">今日史低价</a></li>
            <li><a href="#like-chart" class="waves-effect waves-light">点赞排行榜</a></li>
        </ul>
        <a data-target="nav-mobile" class="sidenav-trigger button"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li>
                <div class="login-form" style="display:inline-table">
                    <input id="autocomplete" type="text" placeholder="搜索品牌(e.g. swisse, ysl)" name="search_content" required>
                </div>
            </li>
            {% if current_user.is_authenticated %}
                <li>
                    <a class="waves-effect waves-light btn orange" href="#my-space">{{ current_user.username }}'s space
                    </a>
                </li>
                <li>
                    <a class="waves-effect waves-light" id="logout-btn" data-href="{{ url_for('auth.logout') }}">
                        <i class="material-icons">power_settings_new</i>
                    </a>
                </li>
            {% else %}
                <li><a class="waves-effect waves-light btn red" href="#signup">Signup</a></li>
                <li><a class="waves-effect waves-light btn red" href="#login">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<main>
    <h3>
        {% if current_user and current_user.is_authenticated %}
            Hi, {{ current_user.username }}!
        {% else %}
            Welcome! Sign up for free!
        {% endif %}
    </h3><br>
    {% block content %}{% endblock %}
</main>
<footer class="center">
    <small> &copy; 2019 Qinghua Wu -
        <a class="blue-text link" href="https://github.com/qinghuawu/ozpricevote" title="Fork me on GitHub">GitHub</a>
    </small>
</footer>
<script>
$( "#autocomplete" ).autocomplete({
  source: "/autocomplete"
});
</script>

PycharmProjects/OZBargainVote/templates/discount_board.html
{% extends 'base.html' %}

{% block content %}
<div align="center" style="font-size:25px">今日史低价</div><br><br>
<table align="center">
    {% for three_products in products %}
    <tr>
        {% for product in three_products %}
        <td>
            {% if current_user and current_user.is_authenticated %}
            {% include '_like_collect.html' %}
            {% endif %}
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle">
                <div align="center" style="width:185px; height:46px">{{ product.title_chinese }}</div>
            </a>
            <div align="center" style="font-size:22px">${{ product.price }}</div>
            <div align="center" style="font-size:22px; color:red">{{ product.discount }} Off</div>
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

PycharmProjects/OZBargainVote/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>
    <title>Home</title>
    <link href="{{ url_for('static', filename='css/materialize.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="//apps.bdimg.com/libs/jqueryui/1.10.4/css/jquery-ui.min.css">
</head>
<body>
<div id="main"></div>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
<script src="//apps.bdimg.com/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";
    var discount_page_url = "{{ url_for('home.discount') }}";
    var cheapest_page_url = "{{ url_for('home.cheapest') }}";
    var like_chart_page_url = "{{ url_for('home.like_chart') }}";
    var signup_url = "{{ url_for('auth.signup') }}";
    var login_url = "{{ url_for('auth.login') }}";
    var logout_url = "{{ url_for('auth.logout') }}";
    var user_space_page_url = "{{ url_for('user.user_space') }}";
    var search_url = "{{ url_for('home.search') }}";
    var autocomplete_url = "{{ url_for('home.autocomplete') }}";
    var my_like_page_url = "{{ url_for('user.my_like') }}";
    var my_collection_page_url = "{{ url_for('user.my_collection') }}";
    var default_error_message = "Oops, something was wrong!";
    var empty_body_error_message = "Your todo was empty!";
    var login_error_message = "Empty username or password!";
</script>
</body>
</html>

PycharmProjects/OZBargainVote/templates/like_board.html
{% extends 'base.html' %}

{% block content %}
<div align="center" style="font-size:25px">点赞排行榜</div><br><br>
{% if not current_user.is_authenticated %}
<h3 align="center">登录以点赞和收藏</h3>
{% endif %}
<ul class="product-list">
    <li style="height:30px; font-size:20px">
        <span style="float:left; padding:0px 60px">商品</span>
        <span style="float:right; padding:0px 70px">点赞数</span>
    </li>
    {% for product in product_info %}
    <li>
        <span style="float:right; font-size:30px; padding:70px 100px">{{ product.like_count }}</span>
        <div style="width:165px; text-align:center">
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle"><br>
                <span style="width:35px; height:46px">{{ product.title_chinese }}</span>
            </a><br><br>
            <span style="font-size:19px">${{ product.price }}</span>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

PycharmProjects/OZBargainVote/templates/my_collection.html
{% extends 'base.html' %}

{% block content %}
<div align="center" style="font-size:25px">{{ current_user.username }}的领地</div><br><br>
<div align="center" style="font-size:29px">
    <a class="snu" href="{{ url_for('my_like') }}">我的点赞</a>
    <a class="snu" href="{{ url_for('my_collection') }}">我的收藏</a>
</div>
<ul class="product-list">
    <li style="height:30px; font-size:20px">
        <span style="float:left; padding:0px 60px">商品</span>
    </li>
    {% for product in products %}
    <li>
        <form method="get" action="{{ url_for('cancel_star', item_id=product.item_id) }}" style="float:right; font-size:30px; padding:70px 100px">
            <input class="snu" type="submit" name="unstar" value="取消收藏" onclick="return confirm('Are you sure?')">
        </form>
        <div style="width:165px; text-align:center">
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle"><br>
                <span style="width:35px; height:46px">{{ product.title_chinese }}</span>
            </a><br><br>
            <span style="font-size:19px">${{ product.price }}</span>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

PycharmProjects/OZBargainVote/templates/my_like.html
{% extends 'base.html' %}

{% block content %}
<div align="center" style="font-size:25px">{{ current_user.username }}的领地</div><br><br>
<div align="center" style="font-size:29px">
    <a class="snu" href="{{ url_for('my_like') }}">我的点赞</a>
    <a class="snu" href="{{ url_for('my_collection') }}">我的收藏</a>
</div>
<ul class="product-list">
    <li style="height:30px; font-size:20px">
        <span style="float:left; padding:0px 60px">商品</span>
    </li>
    {% for product in products %}
    <li>
        <form method="get" action="{{ url_for('cancel_like', item_id=product.item_id) }}" style="float:right; font-size:30px; padding:70px 100px">
            <input class="snu" type="submit" name="unlike" value="取消赞" onclick="return confirm('Are you sure?')">
        </form>
        <div style="width:165px; text-align:center">
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle"><br>
                <span style="width:35px; height:46px">{{ product.title_chinese }}</span>
            </a><br><br>
            <span style="font-size:19px">${{ product.price }}</span>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

PycharmProjects/OZBargainVote/templates/search.html
{% extends 'base.html' %}

{% block content %}
{% if not search_res %}
<h3>没找到您搜的品牌，请换个品牌试试</h3>
{% else %}
<h3>为您找到了{{ num }}件商品</h3>
<table align="center">
    {% for three_products in search_res %}
    <tr>
        {% for product in three_products %}
        <td>
            {% if current_user and current_user.is_authenticated %}
            <form class="inline-form" method="get" action="{{ url_for('star', user_id=current_user.id, item_id=product.item_id) }}">
                <input class="star" type="submit" name="star" value="Star">
            </form>
            <form class="inline-form" method="get" action="{{ url_for('like', user_id=current_user.id, item_id=product.item_id) }}">
                <input class="like" type="submit" name="like" value="Like">
            </form>
            {% endif %}
            <a href="{{ product.url }}">
                <img src="{{ product.image }}" align="middle">
                <div align="center" style="width:185px; height:46px">{{ product.title_chinese }}</div>
            </a>
            <div align="center" style="font-size:22px">${{ product.price }}</div>
            <div align="center" style="font-size:22px; color:red">{{ product.discount }} Off</div>
        </td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% endif %}
{% endblock %}

PycharmProjects/OZBargainVote/templates/user_space.html
{% extends 'base.html' %}

{% block content %}
<div align="center" style="font-size:25px">{{ current_user.username }}的领地</div><br><br>
<div align="center" style="font-size:29px">
    <a class="snu" href="{{ url_for('my_like') }}">我的点赞</a>
    <a class="snu" href="{{ url_for('my_collection') }}">我的收藏</a>
</div><br>
{% endblock %}